### PR TITLE
Add Snapshot to xmeye provider

### PR DESCRIPTION
**Pull request by fogleman**
This takes a picture and returns a JPEG.

### CODE REVIEW

**Comment by kihamo** [comment]
Thanks for your PR. But this command (1560) does not work on my device (video recorder NBD8008RA-GLK). In my case the device always returns (for channel 0, channel active):
`{ "Name" : "OPSNAP", "Ret" : 108, "SessionID" : "0x0000092E" }`

I want to make sure everything works before making changes to the code. What device do you have on which you achieved the result?

I see that other libraries have similar behavior, for example https://github.com/667bdrm/sofiactl/blob/master/sofiactl.pl#L2368

**Comment by fogleman** [comment]
Interesting. It works on my device.

https://green-backyard.com/collections/bird-box-camera/products/wireless-bird-box-camera/

And I used this as a reference: https://github.com/NeiroNx/python-dvr/blob/master/dvrip.py#L781-L793

**Comment by kihamo** [comment]
This seems to be a problem only for videorecorders, devices like cameras are not affected.
I've made changes to the library code, but without your SnapshotImage method. I want to keep the code clean without image processing and I think that the library should only contain with device api interaction. I also added the SnapshotRTSP method, which receives an image from stream RTSP using the popular utility FFMPEG. It's a crutch, but taking a snapshot is a necessary operation and I want to provide an alternative for devices like NBD8008RA-GLK.
I'm still open to ideas, and if you don't have any questions, I'll close this MR. Thank you!

**Comment by fogleman** [comment]
I'm fine with your changes, thanks!

**Pull request closed without merging**
